AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  GetForms:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "icc-forms-getForms-${Environment}"
      CodeUri: forms/getForms/
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          APP_ENV:
            Ref: Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
